# Use the latest Ubuntu image as the base
FROM ubuntu:latest

# Update and upgrade APT packages
RUN apt-get update && apt-get upgrade -y

# Command to run when the container starts
# same as CMD echo "Hello, World!"
CMD ["echo", "Hello, World!"]