services:
  back-end:
    image: "ubuntu:latest"
    environment:
      IS_DOCKER_CONTAINER: 1
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: "docker-task5-back-end"
    restart: always
    ports:
      - "5252:5252"
    networks:
      - private
  front-end:
    image: "nginx:latest"
    environment:
      IS_DOCKER_CONTAINER: 1
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: "docker-task5-front-end"
    restart: always
    ports:
      - "9000:9000"
    networks:
      - private
    depends_on:
      - back-end
  proxy:
    image: "nginx:latest"
    environment:
      IS_DOCKER_CONTAINER: 1
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: "docker-task5-proxy"
    restart: always
    ports:
      - "80:80"
    networks:
      - private
    depends_on:
      - back-end
      - front-end
networks:
  private: